version: '2'
services:
  api:
    image: "lagoon-platform/api"
    ports:
     - "8080:9999"
     
  consul:
    command: -server -bootstrap -advertise 127.0.0.1
    image: "progrium/consul"
    ports:
     - "8300:8300"
     - "8400:8400"
     - "8500:8500"
     - "8600:53/udp"    